// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Client.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace Client.Data.Context.Entities;

[Table("dogadaji")]
public partial class Dogadaji
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("naslov")]
    [StringLength(255)]
    public string Naslov { get; set; }

    [Required]
    [Column("opis")]
    [StringLength(1000)]
    public string Opis { get; set; }

    [Column("vrijeme_objave")]
    public DateTime VrijemeObjave { get; set; }

    [Column("vrijeme_dogadaja")]
    public DateTime VrijemeDogadaja { get; set; }

    [Required]
    [Column("slika")]
    [MaxLength(2000)]
    public byte[] Slika { get; set; }
    
    [Column("autor_id")]
    public int AutorId { get; set; }
    
    [ForeignKey("AutorId")]
    public virtual Korisnici Autor { get; set; }

    [InverseProperty("Dogadaj")]
    public virtual ICollection<KomentariDogadaja> KomentariDogadaja { get; set; } = new List<KomentariDogadaja>();
}