// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Client.Data.Context.Entities;

[Table("komentari_dogadaja")]
public partial class KomentariDogadaja
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("datum")]
    public DateTime Datum { get; set; }

    [Column("ocjena")]
    public int Ocjena { get; set; }

    [Column("komentar")]
    [StringLength(1000)]
    public string Komentar { get; set; }

    [Column("dogadaj_id")]
    public int DogadajId { get; set; }

    [Column("korisnik_id")]
    public int KorisnikId { get; set; }

    [ForeignKey("DogadajId")]
    [InverseProperty("KomentariDogadaja")]
    public virtual Dogadaji Dogadaj { get; set; }
}